// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Eshop.DomainModel.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public bool IsEmailActivated { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int RoleId { get; set; }
}